name: Operational
description: An issue related to operational matters
labels: ["operational"]
type: Operational
projects: ["Symprex/Signature365"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
