name: New Bug
description: Report a bug
labels: ["bug"]
projects: ["Symprex/Signature365"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the fields below to report a new bug, including as much information as possible, including screenshots and links to live examples. A reproduction in our UAT environment is ideal
  - type: dropdown
    id: app
    attributes:
      label: Which app(s) is this bug affecting?
      multiple: true
      options:
        - 'Portal: Customer'
        - 'Portal: Admin'
        - 'Portal: Partner'
        - 'Integration: Outlook Add-In'
        - 'Integration: Outlook Agent'
        - 'Integration: Exchange Transport Agent'
        - 'Integration: Server-Side Injection'
        - 'Connector: Database'
        - 'Connector: Exchange Transport Agent'
        - 'Connector: Entra ID'
        - 'Other'
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - 'Annoying with mitigation'
        - 'Annoying without mitigation'
        - 'Show-stopper'
    validations:
      required: true
  - type: dropdown
    id: env
    attributes:
      label: Which environment can the bug be seen?
      multiple: true
      options:
        - 'UAT'
        - 'Production'
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description / Repro Steps
      description: What is the bug? How can we reproduce it?
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: Mitigation Steps (optional)
      description: Have you tried to workaround the bug? What steps have you tried?
    validations:
      required: false
  - type: textarea
    id: billing
    attributes:
      label: Is this a billing bug? If so please provide additional details (optional)
      description: We need to know whether this is a problem with a specific subscription type such as Credit Card, License Key or Partner. Please provide details and affected tenant link(s) where possible.
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on? (optional)
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: input
    id: support-ticket
    attributes:
      label: Support Ticket (optional)
      description: A link to the FreshDesk ticket reporting the bug
    validations:
      required: false
