name: New Enhancement
description: Request an enhancement/feature
labels: ["enhancement"]
type: Enhancement
projects: ["Symprex/Signature365"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the enhancement?
    validations:
      required: true
  - type: input
    id: support-ticket
    attributes:
      label: Support Ticket (optional)
      description: A link to the Freshdesk ticket requesting this enhancement
    validations:
      required: false
